"""initial schema

Revision ID: 9c56751a319f
Revises: 
Create Date: 2026-07-10 20:29:43.788753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c56751a319f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('filtered_text', sa.Text(), nullable=True),
    sa.Column('sender_name', sa.String(length=100), nullable=True),
    sa.Column('has_violation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_has_violation'), ['has_violation'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)

    op.create_table('forbidden_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forbidden_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forbidden_words_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_forbidden_words_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forbidden_words_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_forbidden_words_word'), ['word'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('violation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('forbidden_word_id', sa.Integer(), nullable=True),
    sa.Column('detected_word', sa.String(length=100), nullable=False),
    sa.Column('position_start', sa.Integer(), nullable=False),
    sa.Column('position_end', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['forbidden_word_id'], ['forbidden_words.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violation_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_logs_forbidden_word_id'), ['forbidden_word_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_logs_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violation_logs_message_id'))
        batch_op.drop_index(batch_op.f('ix_violation_logs_id'))
        batch_op.drop_index(batch_op.f('ix_violation_logs_forbidden_word_id'))
        batch_op.drop_index(batch_op.f('ix_violation_logs_created_at'))

    op.drop_table('violation_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('forbidden_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forbidden_words_word'))
        batch_op.drop_index(batch_op.f('ix_forbidden_words_is_active'))
        batch_op.drop_index(batch_op.f('ix_forbidden_words_id'))
        batch_op.drop_index(batch_op.f('ix_forbidden_words_category'))

    op.drop_table('forbidden_words')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_has_violation'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))

    op.drop_table('chat_messages')
    # ### end Alembic commands ###
